### ISSUE TITLE
Cannot run properly

### ISSUE THREAD

**Issue by misbullah** [gooofy/py-kaldi-simple#1]
Hi,

I tried to run your code. I succeed to get nnet3.so file. Then, I tried to run examples/nnet3_online.py but I get the following error:

Traceback (most recent call last):
  File "examples/nnet3_online.py", line 32, in <module>
    from kaldisimple.nnet3 import KaldiNNet3OnlineDecoder
ImportError: No module named kaldisimple.nnet3

Do you have any idea about this?

**Comment by gooofy** [comment]
have you tried setting your PYTHONPATH env variable?

**Comment by misbullah** [comment]
Hi, 

Thanks for your response.

I think that there is no problem with PYTHONPATH env variable.

When I tried to debug using ipython for each line. This error is showed up:

In [2]: from kaldisimple.nnet3 import KaldiNNet3OnlineDecoder
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-84bd37da9a72> in <module>()
----> 1 from kaldisimple.nnet3 import KaldiNNet3OnlineDecoder

ImportError: kaldisimple/nnet3.so: undefined symbol: _ZTVN3fst11SymbolTableE

I think that something wrong with my Kaldi or GCC version. I use gcc version 5.4.0 in my Ubuntu 16.04 LTS.

How about you?

Thanks,
Alim

**Comment by gooofy** [comment]
yeah, that sure looks like a compiler or linker issue. I am using gcc 4.8.5 on CentOS 7 here.

**Comment by misbullah** [comment]
Hi,

I tried to downgrade my GCC compiler but it does not help. I don't know the problem.

Maybe it is related with FST library.

Thanks,
Alim

**Comment by gooofy** [comment]
ah! that kind-of rings a bell :o) 

at least here, kaldi uses its own openfst library:

[bofh@hal py-kaldi-simple]$ ldd kaldisimple/nnet3.so 
[...]
	libfst.so.1 => /apps/kaldi/tools/openfst-1.3.4/lib/libfst.so.1 (0x00007f229b9e8000)

maybe you have a different openfst library installed somewhere else on your system that nnet3.so accidentially links to?

using ldd, you could also check (for comparison) what kaldi's nnet3 binaries link to, e.g.:

[bofh@hal py-kaldi-simple]$ ldd /apps/kaldi/src/nnet3bin/nnet3-latgen-faster
[...]
	libfst.so.1 => /apps/kaldi/tools/openfst/lib/libfst.so.1 (0x00007f9c0ac65000)

maybe setting your LD_LIBRARY_PATH could help in that case?

**Comment by chief7** [comment]
Hi,

I think I'm facing the very same issue.
I've built kaldi and the shared libs successfully and invoking `make` to build your project creates the `nnet3.so`. But if I try to run your simple sample code, execution stops and complains about the mentioned missing symbol.

The thing is - my `nnet3.so` doesn't link against any `libfst.so`.

This is the output generated by ldd:

> 	linux-vdso.so.1 =>  (0x00007fff0d765000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd5fcd2b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd5fca22000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd5fc80b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd5fc5ed000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd5fc226000)
	/lib64/ld-linux-x86-64.so.2 (0x0000555c7c1c2000)


Do you have any advice if there is still something wrong with my kaldi build? Is there any other hint on how we may fix this?

May we have a look at the output `ldd` generates for your `kaldisimple/nnet3.so`?

Any help is much appreciated. Thanks in advance!

**Comment by gooofy** [comment]
your nnet3.so doesn't seem to be linked against kaldi at all?!

here is mine:
```
[guenter@dagobert py-kaldi-simple]$ ldd ./kaldisimple/nnet3.so
	linux-vdso.so.1 =>  (0x00007ffcea9e3000)
	libfst.so.1 => /apps/kaldi/tools/openfst-1.3.4/lib/libfst.so.1 (0x00007f85af295000)
	libsatlas.so.3 => /usr/lib64/atlas/libsatlas.so.3 (0x00007f85ae4fa000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f85ae2de000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f85ae0da000)
	libkaldi-decoder.so => /apps/kaldi/src/lib/libkaldi-decoder.so (0x00007f85adb37000)
	libkaldi-lat.so => /apps/kaldi/src/lib/libkaldi-lat.so (0x00007f85ad4d2000)
	libkaldi-fstext.so => /apps/kaldi/src/lib/libkaldi-fstext.so (0x00007f85ad277000)
	libkaldi-hmm.so => /apps/kaldi/src/lib/libkaldi-hmm.so (0x00007f85ace57000)
	libkaldi-feat.so => /apps/kaldi/src/lib/libkaldi-feat.so (0x00007f85acbc4000)
	libkaldi-transform.so => /apps/kaldi/src/lib/libkaldi-transform.so (0x00007f85ac914000)
	libkaldi-gmm.so => /apps/kaldi/src/lib/libkaldi-gmm.so (0x00007f85ac682000)
	libkaldi-tree.so => /apps/kaldi/src/lib/libkaldi-tree.so (0x00007f85ac36a000)
	libkaldi-util.so => /apps/kaldi/src/lib/libkaldi-util.so (0x00007f85ac0fd000)
	libkaldi-thread.so => /apps/kaldi/src/lib/libkaldi-thread.so (0x00007f85abef6000)
	libkaldi-matrix.so => /apps/kaldi/src/lib/libkaldi-matrix.so (0x00007f85abbdc000)
	libkaldi-base.so => /apps/kaldi/src/lib/libkaldi-base.so (0x00007f85ab9d3000)
	libkaldi-nnet3.so => /apps/kaldi/src/lib/libkaldi-nnet3.so (0x00007f85ab2e7000)
	libkaldi-online2.so => /apps/kaldi/src/lib/libkaldi-online2.so (0x00007f85aafdb000)
	libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f85aac10000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f85aa906000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f85aa604000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f85aa3ee000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f85aa02c000)
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007f85a9d09000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f85af8da000)
	libkaldi-chain.so => /apps/kaldi/src/lib/libkaldi-chain.so (0x00007f85a9745000)
	libkaldi-cudamatrix.so => /apps/kaldi/src/lib/libkaldi-cudamatrix.so (0x00007f85a94d7000)
	libkaldi-ivector.so => /apps/kaldi/src/lib/libkaldi-ivector.so (0x00007f85a928a000)
	libkaldi-nnet2.so => /apps/kaldi/src/lib/libkaldi-nnet2.so (0x00007f85a8d9c000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f85a8b99000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f85a895c000)
```

**Comment by chief7** [comment]
Yeah, I kind of feared that there has to be some issue .. ;-) 

Any specific steps to build `kaldisimple/nnet3.so`? If not I guess this might be kaldi related and has nothing to do with your project ...

But thanks so far!

**Comment by gooofy** [comment]
there is not much to building nnet3.so other than setting the kaldi root path in the Makefile and run make.

could you do a

`make clean all`

to check the compiler/linker commandline?

**Comment by chief7** [comment]
thanks for your help so far ...

Here is my linker / compiler command line. Please note that I had to change compiling standard to gnu++98 in order get compilation done.

> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -I/code/kaldi/src -std=gnu++98 -msse -msse2 -Wall -I.. -pthread -D
KALDI_DOUBLEPRECISION=0 -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/code/kaldi/tools/ATLAS/include -I/
home/zorc/code/kaldi/tools/openfst/include -g -fPIC -I/home/zorc/.local/lib/python2.7/site-packages/numpy/core/include -I/code/kaldi/src -I/code/kaldi/tools/
openfst/include -I/code/kaldi/tools/ATLAS/include -I/usr/include/python2.7 -c kaldisimple/nnet3.cpp -o build/temp.linux-x86_64-2.7/kaldisimple/nnet3.o

> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -I/code/kaldi/src -std=gnu++98 -msse -msse2 -Wall -I.. -pthread -D
KALDI_DOUBLEPRECISION=0 -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/code/kaldi/tools/ATLAS/include -I/
home/zorc/code/kaldi/tools/openfst/include -g -fPIC -I/home/zorc/.local/lib/python2.7/site-packages/numpy/core/include -I/code/kaldi/src -I/code/kaldi/tools/
openfst/include -I/code/kaldi/tools/ATLAS/include -I/usr/include/python2.7 -c kaldisimple/nnet3_wrappers.cpp -o build/temp.linux-x86_64-2.7/kaldisimple/nnet3_wrappers.o

> c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D
_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-lMBuS3/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -L/code/kaldi/tools/openfs
t/lib -L/code/kaldi/src/lib -lfst -lm -lpthread -ldl -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lk
aldi-util -lkaldi-thread -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -I/code/kaldi/src -std=gnu++98 -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECIS
ION=0 -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/code/kaldi/tools/ATLAS/include -I/home/zorc/code/kal
di/tools/openfst/include -g build/temp.linux-x86_64-2.7/kaldisimple/nnet3.o build/temp.linux-x86_64-2.7/kaldisimple/nnet3_wrappers.o -o /home/zorc/code/py-kaldi-simple/kaldisimp
le/nnet3.so


I know this is lots of stuff but maybe you see some hints? It should link against kaldi from what I can tell. Shared libs are all there... Maybe you could drop yours again so that I could compare them?

Well thanks again!

**Comment by gooofy** [comment]
you seem to have two different paths to your kaldi installation in there: sometimes it's `/home/zorc/code/kaldi`, other times simply `/code/kaldi`. 

Just a wild guess: maybe you specified a relative path somewhere where the build mechanism expects an absolute one?

**Comment by chief7** [comment]
oh sorry, no that's actually symlinked. I removed the link for testing purposes but it's still the same issue. 

It's very strange that there is no linking against the kaldi libs at all ...

By the way: I had to change the atlas-path too. Does ring any bells?

**Comment by gooofy** [comment]
sorry, not really, no ... I do know kaldi needs its own version of openfst (AFAIK that is realted to c++ standards and being discussed right now), but other than that I did not have to do anything special to get kaldi and/or my python wrapper compiled.

just for reference, here is my linker invocation:

```
g++ -pthread -shared -Wl,-z,relro -rdynamic -L/apps/kaldi/tools/openfst/lib -L/apps/kaldi/src/lib -lfst /usr/lib64/atlas/libsatlas.so -lm -lpthread -ldl -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-thread -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -I/apps/kaldi/src -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/apps/kaldi/tools/ATLAS/include -I/apps/kaldi/tools/openfst/include -g build/temp.linux-x86_64-2.7/kaldisimple/nnet3.o build/temp.linux-x86_64-2.7/kaldisimple/nnet3_wrappers.o -L/usr/lib64 -lpython2.7 -o /home/guenter/projects/hal9000/mainframe/py-kaldi-simple/kaldisimple/nnet3.so
[guenter@dagobert py-kaldi-simple]$ ldd /home/guenter/projects/hal9000/mainframe/py-kaldi-simple/kaldisimple/nnet3.so
	linux-vdso.so.1 =>  (0x00007ffd85d9c000)
	libfst.so.1 => /apps/kaldi/tools/openfst-1.3.4/lib/libfst.so.1 (0x00007f0b1121d000)
	libsatlas.so.3 => /usr/lib64/atlas/libsatlas.so.3 (0x00007f0b10482000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0b10266000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0b10062000)
	libkaldi-decoder.so => /apps/kaldi/src/lib/libkaldi-decoder.so (0x00007f0b0fabf000)
	libkaldi-lat.so => /apps/kaldi/src/lib/libkaldi-lat.so (0x00007f0b0f45a000)
	libkaldi-fstext.so => /apps/kaldi/src/lib/libkaldi-fstext.so (0x00007f0b0f1ff000)
	libkaldi-hmm.so => /apps/kaldi/src/lib/libkaldi-hmm.so (0x00007f0b0eddf000)
	libkaldi-feat.so => /apps/kaldi/src/lib/libkaldi-feat.so (0x00007f0b0eb4c000)
	libkaldi-transform.so => /apps/kaldi/src/lib/libkaldi-transform.so (0x00007f0b0e89c000)
	libkaldi-gmm.so => /apps/kaldi/src/lib/libkaldi-gmm.so (0x00007f0b0e60a000)
	libkaldi-tree.so => /apps/kaldi/src/lib/libkaldi-tree.so (0x00007f0b0e2f2000)
	libkaldi-util.so => /apps/kaldi/src/lib/libkaldi-util.so (0x00007f0b0e085000)
	libkaldi-thread.so => /apps/kaldi/src/lib/libkaldi-thread.so (0x00007f0b0de7e000)
	libkaldi-matrix.so => /apps/kaldi/src/lib/libkaldi-matrix.so (0x00007f0b0db64000)
	libkaldi-base.so => /apps/kaldi/src/lib/libkaldi-base.so (0x00007f0b0d95b000)
	libkaldi-nnet3.so => /apps/kaldi/src/lib/libkaldi-nnet3.so (0x00007f0b0d26f000)
	libkaldi-online2.so => /apps/kaldi/src/lib/libkaldi-online2.so (0x00007f0b0cf63000)
	libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f0b0cb98000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f0b0c88e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f0b0c58c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f0b0c376000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0b0bfb4000)
	libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007f0b0bc91000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0b11862000)
	libkaldi-chain.so => /apps/kaldi/src/lib/libkaldi-chain.so (0x00007f0b0b6cd000)
	libkaldi-cudamatrix.so => /apps/kaldi/src/lib/libkaldi-cudamatrix.so (0x00007f0b0b45f000)
	libkaldi-ivector.so => /apps/kaldi/src/lib/libkaldi-ivector.so (0x00007f0b0b212000)
	libkaldi-nnet2.so => /apps/kaldi/src/lib/libkaldi-nnet2.so (0x00007f0b0ad24000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f0b0ab21000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f0b0a8e4000)

```

I guess we may have different compilers here - I am using

```
[guenter@dagobert py-kaldi-simple]$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

from CentOS 7 here.

**Comment by chief7** [comment]
Thanks so far! I'll be home at the end of the week and then I'll check on that!

**Comment by chief7** [comment]
Just for the record and maybe as an additional information to everyone reading this:

In order to get everything to work I had to do the steps listed below:

- Build kaldi with shared libs
- Change kaldi root in Makefile as described
- I had to add `-std=c++11` to CLFAGS since I decided to use OpenBLAS instead of ATLAS
- Change path from `libatlas.so` to `libopenblas.so` (Makefile)
- Add include paths for openfst, OpenBLAS and kaldi to setup.py.
- Add `-std=c++11` to setup.py
And maybe the most important step: Using a newer version of gcc/g++ as 4.8 changes the behaviour of ld and you have to add `-Wl,-no-as-needed` to LDFLAGS to link against supplied libraries even if not referenced at compile time.

But once this is done you code works like a charm. I juist did a quick test using your voxforge models - it rocks!

Thanks again!

**Comment by gooofy** [comment]
very cool - thanks for the feedback!

**Comment by misbullah** [comment]
Hi, 

I follow the instruction from chief7. It can work now. The important thing is that Kaldi need to build using shared library (in kaldi/src --> ./configure --shared) 

Thanks  a lot.

**Comment by migueljette** [comment]
Hi @chief7 ,

When you say `Add include paths for openfst, OpenBLAS and kaldi to setup.py.`, can you show me how exactly?

Also, when you say `you have to add -Wl,-no-as-needed to LDFLAGS`, where exactly do you add it in the existing LDFLAGS lines?

Thanks for your help!
I'd love to get this working. Very exciting!

**Comment by chief7** [comment]
Hi, sure ... I've just created a fork and will upload my changes tomorrow so you may have a look. It's easier to show than to explain.

**Comment by migueljette** [comment]
Sounds good! Thank you for the help!

**Comment by gooofy** [comment]
@chief7: I am also looking forward to see what you have done. maybe we can merge back your changes?

**Comment by chief7** [comment]
@migueljette Please see my fork here and compare it to gooofys. This should indicate you where you have to change things:
https://github.com/chief7/py-kaldi-simple

@gooofy Sure, I'd love to contribute! But I guess it may be more useful to commit a configure shell script or sth like that. I may have time during the next days and could come up with a first idea

**Comment by migueljette** [comment]
Maybe my setup is too different:

```
g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
```

I am never able to link properly:
```
ldd ./kaldisimple/nnet3.so
       	linux-vdso.so.1 =>  (0x00007ffdc398b000)
       	libfst.so.1 => not found
       	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4c5a597000)
       	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4c5a392000)
       	libkaldi-decoder.so => not found
       	libkaldi-lat.so => not found
       	libkaldi-fstext.so => not found
       	libkaldi-hmm.so => not found
       	libkaldi-feat.so => not found
       	libkaldi-transform.so => not found
       	libkaldi-gmm.so => not found
       	libkaldi-tree.so => not found
       	libkaldi-util.so => not found
       	libkaldi-thread.so => not found
       	libkaldi-matrix.so => not found
       	libkaldi-base.so => not found
       	libkaldi-nnet3.so => not found
       	libkaldi-online2.so => not found
       	libpython2.7.so.1.0 => /home/rave/anaconda2/lib/libpython2.7.so.1.0 (0x00007f4c59f91000)
       	libstdc++.so.6 => /home/rave/anaconda2/lib/libstdc++.so.6 (0x00007f4c59c7b000)
       	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4c59972000)
       	libgcc_s.so.1 => /home/rave/anaconda2/lib/libgcc_s.so.1 (0x00007f4c5975b000)
       	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c59392000)
       	/lib64/ld-linux-x86-64.so.2 (0x0000555d283c9000)
       	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f4c5918f000)
```

**Comment by chief7** [comment]
Well, it seems as if your `nnet3.so` is linked against your shared kaldi libraries but your system can't find them. What you have to do is to add them to your ldconfig. 

Usually you have a directory `/etc/ld.so.conf.d` which contains files with include paths for ld. So you should add a file to that directory, e.g. `kaldi.conf` which contains the path to your kaldi *.so files. Then check back with `ldd` if it works.

Edit: don't forget to reload your ldconfig after that. `sudo ldconfig`

**Comment by migueljette** [comment]
Hi, thanks for the support!
What does the kaldi.conf file look like?
A list of the *so files?
Like this?
```
/home/<USER>/kaldi/src/lib/libkaldi-base.so
/home/<USER>/kaldi/src/lib/libkaldi-chain.so
...
```

It didn't work. But maybe I need to re-read your instructions above.
I am trying to use ATLAS  instead of openBLAS... any reasons I should switch to the same as you?

**Comment by chief7** [comment]
Hi, its more like
```/home/<USER>/kaldi/src/lib```

It's basically just telling your system where to look for shared libraries not exactly what files to use.

It should work with ATLAS since gooofy and everyone else I've seen using kaldi is using it, no need to change.

**Comment by chief7** [comment]
Did you build ATLAS yourself or did you use the one that comes with kaldi?

**Comment by migueljette** [comment]
I'm using the one from Kaldi.

It is looking better, but now i have this:
```
ldd ./kaldisimple/nnet3.so
./kaldisimple/nnet3.so: /home/<USER>/anaconda2/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/<USER>/kaldi/src/lib/libkaldi-decoder.so)
       	linux-vdso.so.1 =>  (0x00007fff32dd7000)
       	libfst.so.1 => not found
       	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fec75836000)
       	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fec75631000)
       	libkaldi-decoder.so => /home/<USER>/kaldi/src/lib/libkaldi-decoder.so (0x00007fec75067000)
```
Should I use python3?

**Comment by chief7** [comment]
Did you built kaldi from source? And no, gooofys scripts are python2 only.

**Comment by migueljette** [comment]
Yes. With the --shared flag.

**Comment by migueljette** [comment]
Ok, i fixed the error `version `GLIBCXX_3.4.21' not found` by updating libgcc in anaconda:
```
conda install libgcc
```

I can see it in here:
```
strings /home/<USER>/anaconda2/lib/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_DEBUG_MESSAGE_LENGTH
...
GLIBCXX_3.4.20
GLIBCXX_3.4.21
```

But my "fst" package still isn't linked.
I will continue to poke around and see the differences with your setup.py.

**Comment by chief7** [comment]
Ok, I don't have any experience with anaconda but good to hear that you figured that out.

You `nnet3.so` was linked against libfst.so.1 earlier. So maybe check that your libfst.so is known to the system. Kaldi keeps it's copy within `kaldi/tools/openfst/lib` or someting like that.

**Comment by migueljette** [comment]
Ok, it is linked. I had to add the openfst path to /etc/ld.so.conf.d/kaldi.conf.

But my first line is still bad:
```
ldd ./kaldisimple/nnet3.so
       	linux-vdso.so.1 =>  (0x00007fff5e2cd000)
```
I'll continue to poke around. :)

**Comment by migueljette** [comment]
Wow. After all of this. :)

My issue showed up as:
```
python examples/nnet3_online.py
Traceback (most recent call last):
  File "examples/nnet3_online.py", line 32, in <module>
    from kaldisimple.nnet3 import KaldiNNet3OnlineDecoder
ImportError: No module named kaldisimple.nnet3
```

I did have a bunch of issues with the way I linked to kaldi. So thanks to @chief7 for all your help!

In the end though, after checking that everything was linked properly, I was still getting the same issue... so i decided to debug the python call, as it was suggested above... line by line.

The problem was that I was calling the script like this:
```
python examples/nnet3_online.py
```

When you move the script to the same folder, then you get the expected result:
```
python nnet3_online.py
```

Maybe I need to add something to my PATH?
Very weird, but it works now!

I'm off to trying to use my own model now.
Thank you for all the support!!!

**Comment by chief7** [comment]
Glad to see that it's working now!

**Comment by gooofy** [comment]
very cool to see you got this issue sorted! :) - If you have any patches/suggestions, please let me know.

**Comment by mariasmo** [comment]
hi chief7,

i am trying to work on this sample and ran into lots of issues(too many to post here).
Then i saw this issue and started following so that i can use C++11 standard as well.
I have a question. I took the following command from your git repo

CFLAGS = -I$(KALDI_ROOT)/src -std=c++11 -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -Wno-sign-compare \
         -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_OPENBLAS -DHAVE_OPENFST_GE_10400 \
		 -I/home/zorc/code/OpenBLAS/lib/include -I$(KALDI_ROOT)/tools/openfst/include -g

So in it you use OpenBLAS and say -DHAVE_OPENBLAS

But when you compile kaldi, i am assuming you did not specify the OpenBLAS options, correct? If that is the case then I believe kaldi would have used ATLAS by default. Is that true?

Or will kaldi use the flags from the above mentioned command that has -DHAVE_OPENBLAS in the flags?

Thanks in advance

**Comment by mariasmo** [comment]
hi chief7

never mind. i was able to go past all my errors but i am still having one error which has been reported in issue #4 already 

In file included from kaldisimple/nnet3.cpp:246:0:
kaldisimple/nnet3_wrappers.h:63:9: error: 'OnlineNnet3DecodingConfig' does not name a type
         OnlineNnet3DecodingConfig                 nnet3_decoding_config;   

I am awaiting response from maelp on that issue.

I have one question though. You have used -DHAVE_OPENFST_GE_10400

is it because you are using a dfferent openfst than the kaldi one? i did not use the above option though.

thanks

**Comment by shturag** [comment]
@migueljette 
Hi, I was trying with pertained model in Mac:
got same error.

Shakhawats-MBP:goofy_zamia shakhawat_hossain_turag$ python kaldi_decode_wav.py -v demo?.wav
Traceback (most recent call last):
  File "kaldi_decode_wav.py", line 36, in <module>
    from kaldiasr.nnet3 import KaldiNNet3OnlineModel, KaldiNNet3OnlineDecoder
ImportError: No module named kaldiasr.nnet3

Would you please let me know. How did you solve that?

**Comment by migueljette** [comment]
From my comment above, it looks like I moved a script to a different folder. Read my Feb 8th comment to see. Good luck!

**Comment by shturag** [comment]
Thanks for your reply. I have seen that but a bit confused where the folder is actually located. And I couldn't install py-kaldi-asr with pip install. It might be problem with that. Btw have u installed py-kaldi-asr in python before?

**Comment by migueljette** [comment]
Unfortunately, I have not used this repo in 3 years, so i am sure it has changed a lot since I used it. 
Probably not having installed via pip is a good sign that something is wrong. Maybe kaldi is not installed properly as well. 
Good luck!
