### ISSUE TITLE
setup.py: Issue with numpy dependency

### ISSUE THREAD

**Issue by mpuels** [gooofy/py-kaldi-simple#11]
The file [setup.py](https://github.com/gooofy/py-kaldi-asr/blob/79059f846501cbd7db216b8cb34c3e84a27f6be3/setup.py#L3) imports `numpy` at the top, but this will fail if `numpy` isn't installed on the system yet. So a simple `pip install py-kaldi-asr` is not possible on a newly set up Python environment. But adding `numpy` to `install_requires` won't help either, because `pip` runs `setup.py` to find out the package's requirements. 

There seem to be solutions, but they're not clean (see [How to Bootstrap numpy installation in setup.py
](https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py)).

Maybe you can mark this issue as low priority.

**Comment by gooofy** [comment]
Thanks for the report. I guess nesting the import statement somewhere into a helper function as suggested in the stackoverflow answers seems like a good option to me. Unfortunately I have no easy way of testing this right now (all my machines do have numpy installed and removing it for test purposes is a pain) but in theory this approach should work.

**Comment by gooofy** [comment]
putting this issue into the backlog for now.
