### ISSUE TITLE
Error while loading nnet3 model

### ISSUE THREAD

**Issue by embie27** [gooofy/py-kaldi-simple#12]
When running your nnet3_online.py example, I get the following error:
```tdnn_sp loading model...
Traceback (most recent call last):
  File "py-kaldi-test.py", line 21, in <module>
    kaldi_model = KaldiNNet3OnlineModel (MODELDIR, model)
  File "kaldiasr/nnet3.pyx", line 52, in kaldiasr.nnet3.KaldiNNet3OnlineModel.__cinit__
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string
TypeError: expected bytes, str found```

**Comment by gooofy** [comment]
just gave it a test run, worked for me:

[guenter@dagobert py-kaldi-asr]$ python examples/nnet3_online.py 
nnet_tdnn_a loading model...
nnet_tdnn_a loading model... done.
nnet_tdnn_a decoding worked!

*****************************************************************
** data/single.wav
** aber noch nicht veröffentlicht worden 
** nnet_tdnn_a likelihood: 0.363921701908
** word alignment: :
**   0.000000	0.870000	<eps>
**   0.870000	1.370000	aber
**   1.370000	1.400000	<eps>
**   1.400000	1.670000	noch
**   1.670000	2.040000	nicht
**   2.040000	2.900000	veröffentlicht
**   2.900000	3.440000	worden
**   3.440000	4.860000	<eps>
*****************************************************************

nnet_tdnn_a decoding took     1.36s
nnet_tdnn_a decoding worked!

**Comment by cogmeta** [comment]
Hi @gooofy , I am getting same extact error as @embie27.

INFO:root:model loading model from /opt/kaldi-model ...
Traceback (most recent call last):
  File "cogmeta_asr_local.py", line 211, in <module>
    nnet3_model = KaldiNNet3OnlineModel (kaldi_model_dir, kaldi_model)
  File "kaldiasr/nnet3.pyx", line 134, in kaldiasr.nnet3.KaldiNNet3OnlineModel.__cinit__
RuntimeError

**Comment by cogmeta** [comment]
It works for kaldi-generic-en-tdnn_250-r20180815 but NOT for kaldi-generic-en-tdnn_f-r20180901

**Comment by gooofy** [comment]
> It works for kaldi-generic-en-tdnn_250-r20180815 but NOT for kaldi-generic-en-tdnn_f-r20180901

this could be an indication that your kaldi installation is outdated
(tdnn_f is a fairly recent feature in kaldi)

**Comment by chrisspen** [comment]
The error appears to be coming from a Cython/C-extension. Is it possible there might be some missing dependency that caused the py-kaldi-asr package to incorrectly compile without throwing an explicit error? It appeared to compile just fine for me.
