### ISSUE TITLE
Troubles with running example script "examples/nnet3_online.py"

### ISSUE THREAD

**Issue by sergy5** [gooofy/py-kaldi-simple#13]
Hello!
I successfully installed py-kaldi-asr. But when I run "examples/nnet3_online.py", I get the following error:
Traceback (most recent call last):
  File "examples/nnet3_online.py", line 32, in <module>
    from kaldiasr.nnet3 import KaldiNNet3OnlineModel, KaldiNNet3OnlineDecoder
  File "build/bdist.linux-x86_64/egg/kaldiasr/nnet3.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/kaldiasr/nnet3.py", line 6, in __bootstrap__
ImportError: /home/kazan/.cache/Python-Eggs/py_kaldi_asr-0.2.4-py2.7-linux-x86_64.egg-tmp/kaldiasr/nnet3.so: undefined symbol: FLAGS_fst_error_fatal

Could you help me with it?

**Comment by gooofy** [comment]
Hi sergy5,

haven't seen this problem before, but from the looks of it it seems to indicate a problem with your openfst installation - please make sure you use the same one you compiled kaldi and py-kaldi-asr against (typically you want to use the one that kaldi comes with in its tools/ directory for everything)

best,

   guenter
