### ISSUE TITLE
pkg-config related issue

### ISSUE THREAD

**Issue by truAkshayR** [gooofy/py-kaldi-simple#14]
Hi,

I'm installing py-kaldi-asr via pip on condaenv, but I'm getting this error:

Collecting py-kaldi-asr
  Using cached https://files.pythonhosted.org/packages/be/c9/b25dd5d9d5621a8e3327b931e22e69ee256c50767c3646b087c9f05047fd/py-kaldi-asr-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Package kaldi-asr was not found in the pkg-config search path.
    Perhaps you should add the directory containing `kaldi-asr.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'kaldi-asr' found
    looking for atlas library, trying pkg-config first...
    looking for atlas library, pkg-config found it
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2tNyTW/py-kaldi-asr/setup.py", line 99, in <module>
        **find_dependencies()),
      File "/tmp/pip-build-2tNyTW/py-kaldi-asr/setup.py", line 72, in find_dependencies
        raise Exception("*** failed to find pkgconfig for kaldi-asr")
    Exception: *** failed to find pkgconfig for kaldi-asr
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2tNyTW/py-kaldi-asr/

I had encountered a similar issue with the .pc file for Atlas, but managed a workaround(as the file was in a different dir) but I'm completely lost at this, mostly because I just got swamped with some other work.

System:
Ubuntu 18.04 on Oracle Virtualbox (Host Windows 8)
Python 2.7 (Anaconda) (but I'm using "pip" for this and not "conda")

Thanks!(This is my first git issue ever)

unnecessary comment: What's the deal with pkg-config anyway?

**Comment by svenha** [comment]
Did you write kaldi-asr.pc as described in https://github.com/gooofy/py-kaldi-asr#source ?

**Comment by truAkshayR** [comment]
Sorry my mistake, it was really dumb of me to miss/overlook that.

Just did as you pointed, it worked!

Thanks a bunch!
Shall I close the issue?

**Comment by svenha** [comment]
Good to hear that it worked for you. You can close the issue, if you want.

**Comment by Cloud299** [comment]
Having a similar issue. Created kaldi-asr.pc and put it within py-kaldi-asr folder. I then did "export PK_CONFIG_PATH=/path/to/py-kaldi-asr". Note that "/path/to/py-kaldi-asr" is my local path to py-kaldi-asr. But still it gives the error:
python setup.py build_ext --inplace
looking for atlas library, trying pkg-config first...
Package atlas was not found in the pkg-config search path.
Perhaps you should add the directory containing `atlas.pc'
to the PKG_CONFIG_PATH environment variable
No package 'atlas' found
looking for atlas library, trying hard-coded paths...
looking for atlas library, found it.
Package kaldi-asr was not found in the pkg-config search path.
Perhaps you should add the directory containing `kaldi-asr.pc'
to the PKG_CONFIG_PATH environment variable
No package 'kaldi-asr' found
Traceback (most recent call last):
  File "setup.py", line 99, in <module>
    **find_dependencies()),
  File "setup.py", line 72, in find_dependencies
    raise Exception("*** failed to find pkgconfig for kaldi-asr")
Exception: *** failed to find pkgconfig for kaldi-asr
Makefile:12: recipe for target 'kaldiasr/nnet3.so' failed

**Comment by svenha** [comment]
Do you really think that /path/to/py-kaldi-asr should not be adjusted to your case? :-)

**Comment by Cloud299** [comment]
Of course I adjusted to my case :) I just wrote it that way to not show unnecessary information

**Comment by svenha** [comment]
OK. As the problem seems to be right there, please include this information.

**Comment by Cloud299** [comment]
Information included. Any idea how to fix this ?

**Comment by gooofy** [comment]
> I then did "export PK_CONFIG_PATH=/path/to/py-kaldi-asr"

you got a typo in the variable name there, try "PKG_CONFIG_PATH" instead.

**Comment by Cloud299** [comment]
Same error. Sorry I made a typo here on git

**Comment by gooofy** [comment]
please try

`pkg-config --cflags kaldi-asr --debug`

and check the output to see what is going on, then.

here is mine:

```
[...]
Looking for package 'kaldi-asr'
Looking for package 'kaldi-asr-uninstalled'
Reading 'kaldi-asr' from file '/usr/lib64/pkgconfig/kaldi-asr.pc'
Parsing package file '/usr/lib64/pkgconfig/kaldi-asr.pc'
  line>kaldi_root=/opt/kaldi
 Variable declaration, 'kaldi_root' has value '/opt/kaldi'
  line>
  line>Name: kaldi-asr
  line>Description: kaldi-asr speech recognition toolkit
  line>Version: 5.4
  line>Requires: atlas openfst
Looking for package 'atlas'
Looking for package 'atlas-uninstalled'
Reading 'atlas' from file '/usr/lib64/pkgconfig/atlas.pc'
Parsing package file '/usr/lib64/pkgconfig/atlas.pc'
  line>Name: atlas
  line>Version: 3.10.2
  line>Description: Debug information for package atlas
  line>Cflags: -I/usr/include/atlas/
  line>Libs: -L/usr/lib64/atlas/ -lsatlas
Path position of 'atlas' is 1
Adding 'atlas' to list of known packages, returning as package 'atlas'
Looking for package 'openfst'
Looking for package 'openfst-uninstalled'
Reading 'openfst' from file '/usr/lib64/pkgconfig/openfst.pc'
Parsing package file '/usr/lib64/pkgconfig/openfst.pc'
  line>Name: openfst
  line>Description: Weighted finite-state transducer library
  line>Version: 1.6.7
  line>Libs: -lfst
Path position of 'openfst' is 1
Adding 'openfst' to list of known packages, returning as package 'openfst'
  line>Libs: -L${kaldi_root}/src/lib -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector
  line>Cflags: -I${kaldi_root}/src
Path position of 'kaldi-asr' is 1
Adding 'kaldi-asr' to list of known packages, returning as package 'kaldi-asr'
 original:  kaldi-asr  atlas  openfst 
 sorted:  kaldi-asr  atlas  openfst 
 original:  kaldi-asr  atlas  openfst 
 sorted:  kaldi-asr  atlas  openfst 
-I/opt/kaldi/src -I/usr/include/atlas/  

```

**Comment by Cloud299** [comment]
Mine says:
`Variable declaration, 'kaldi_root' has value '/testing/kaldi'
  line>
  line>Name: kaldi-asr
  line>Description: kaldi-asr speech recognition toolkit
  line>Version: 5.2
  line>Requires: atlas
  line>Libs: -L${kaldi_root}/tools/openfst/lib -L${kaldi_root}/src/lib -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector -lfst
  line>Cflags: -I${kaldi_root}/src  -I${kaldi_root}/tools/openfst/include
  line>
Path position of 'kaldi-asr' is 1
Adding 'kaldi-asr' to list of known packages
Searching for 'kaldi-asr' requirement 'atlas'
Looking for package 'atlas'
Looking for package 'atlas-uninstalled'
Package atlas was not found in the pkg-config search path.
Perhaps you should add the directory containing `atlas.pc'
to the PKG_CONFIG_PATH environment variable`

**Comment by Cloud299** [comment]
Mine says:
`Variable declaration, 'kaldi_root' has value '/testing/kaldi'
  line>
  line>Name: kaldi-asr
  line>Description: kaldi-asr speech recognition toolkit
  line>Version: 5.2
  line>Requires: atlas
  line>Libs: -L${kaldi_root}/tools/openfst/lib -L${kaldi_root}/src/lib -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector -lfst
  line>Cflags: -I${kaldi_root}/src  -I${kaldi_root}/tools/openfst/include
  line>
Path position of 'kaldi-asr' is 1
Adding 'kaldi-asr' to list of known packages
Searching for 'kaldi-asr' requirement 'atlas'
Looking for package 'atlas'
Looking for package 'atlas-uninstalled'
Package atlas was not found in the pkg-config search path.
Perhaps you should add the directory containing `atlas.pc'
to the PKG_CONFIG_PATH environment variable`

**Comment by gooofy** [comment]
ah, there you got your answer: it fails to find the atlas package on your system :)

**Comment by Cloud299** [comment]
Mine says:

File 'systemd.pc' appears to be a .pc file
Will find package 'systemd' in file '/usr/share/pkgconfig/systemd.pc'
Looking for package 'kaldi-asr'
Looking for package 'kaldi-asr-uninstalled'
Reading 'kaldi-asr' from file '/home/test/py-kaldi-asr/kaldi-asr.pc'
Parsing package file '/home/test/py-kaldi-asr/kaldi-asr.pc'
  line>kaldi_root=/home/test/kaldi
 Variable declaration, 'kaldi_root' has value '/home/test/kaldi'
  line>
  line>Name: kaldi-asr
  line>Description: kaldi-asr speech recognition toolkit
  line>Version: 5.2
  line>Requires: atlas
  line>Libs: -L${kaldi_root}/tools/openfst/lib -L${kaldi_root}/src/lib -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector -lfst
  line>Cflags: -I${kaldi_root}/src  -I${kaldi_root}/tools/openfst/include
  line>
Path position of 'kaldi-asr' is 1
Adding 'kaldi-asr' to list of known packages
Searching for 'kaldi-asr' requirement 'atlas'
Looking for package 'atlas'
Looking for package 'atlas-uninstalled'
Package atlas was not found in the pkg-config search path.
Perhaps you should add the directory containing `atlas.pc'
to the PKG_CONFIG_PATH environment variable
Package 'atlas', required by 'kaldi-asr', not found

**Comment by Cloud299** [comment]
Hmm, am I missing something when installing kaldi-asr. I followed instruction at https://github.com/kaldi-asr/kaldi/blob/master/tools/INSTALL

**Comment by Cloud299** [comment]
Hmmm, am I missing something when installing kaldi-asr? I followed instruction here https://github.com/kaldi-asr/kaldi/blob/master/tools/INSTALL

**Comment by gooofy** [comment]
I think your pkg-config setup is incomplete, you will need to tell pkg-config about your atlas library installation. to check, run

`pkg-config --cflags atlas`

I suspect that will not work on your setup.

**Comment by Cloud299** [comment]
I got:
Package atlas was not found in the pkg-config search path.
Perhaps you should add the directory containing `atlas.pc'
to the PKG_CONFIG_PATH environment variable
No package 'atlas' found
I see atlas at /usr/include/atlas. However I don't see 'atlas.pc' here. How to I tell pkg-config about atlas ?

**Comment by svenha** [comment]
If I recall correctly, I had to change lines 53-56 in setup.py as follows (because /usr/include/x86_64-linux-gnu/atlas is the correct path on Ubuntu and Ubuntu has no file atlas.pc):
`        if os.path.isdir('/usr/include/atlas'):`
`              kw.setdefault('include_dirs', []).append('/usr/include/atlas')`
`         elif os.path.isdir('/usr/include/x86_64-linux-gnu/atlas'):`
`              kw.setdefault('include_dirs', []).append('/usr/include/x86_64-linux-gnu/atlas')`
`         else:`
`               raise Exception ('Failed to find atlas includes your system.')`

Do you know which package created /usr/include/atlas? Can you show the output of uname -a?

**Comment by Cloud299** [comment]
Modified setup.py as suggested. Still got the same error. 
Output of uname -a is:
Linux ip_adress 4.4.0-1067-aws #77-Ubuntu SMP Mon Aug 27 13:22:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by svenha** [comment]
I am sorry. I only have experience with Kaldi and Ubuntu 17.04 till 18.10 and not 16.04. Obviously, they changed some installation details for atlas after 16.04. BTW: If you want to train models, you will probably need a GPU (just mentioning it because of the -aws part in your kernel identifier).

**Comment by svenha** [comment]
One more idea. I compared my kaldi-asr.pc to the one documented here: I have no Requires line. This makes sense because the atlas configuration can be done without pkg-config.

**Comment by Cloud299** [comment]
> One more idea. I compared my kaldi-asr.pc to the one documented here: I have no Requires line. This makes sense because the atlas configuration can be done without pkg-config.

Could you elaborate on this ? Also, I'm trying to perform speech-to-text for .wav files using kaldi pre-trained models so I'm not thinking about training my own models as of now

**Comment by svenha** [comment]
My suggestion is: delete the Requires line in your kaldi-asr.pc and run 'setup.py' again.

**Comment by Cloud299** [comment]
Tried it. Still got the error: 
looking for atlas library, trying pkg-config first...
Package atlas was not found in the pkg-config search path.
Perhaps you should add the directory containing `atlas.pc'
It's still looking to configure atlas with pkg-config. 
My kaldi-asr.pc looks like:
kaldi_root=/home/test/kaldi

Name: kaldi-asr
Description: kaldi-asr speech recognition toolkit
Version: 5.2
Libs: -L${kaldi_root}/tools/openfst/lib -L${kaldi_root}/src/lib -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector -lfst
Cflags: -I${kaldi_root}/src  -I${kaldi_root}/tools/openfst/include

**Comment by svenha** [comment]
> looking for atlas library, trying pkg-config first...

Yes, and "first" means it will make a second try, with "looking for atlas library, trying hard-coded paths...", see setup.py. From time to time, you might have to look into the code ... You have been warned :-)

**Comment by Cloud299** [comment]
Looked into setup.py and saw that it was trying to find where libatlas.so.3 is. Found it at /usr/lib/atlas-base/atlas) and included the path in setup.py. I no longer have that error. Thanks for the suggestion @svenha 

Running into a different issue when running "make":

warning: no library file corresponding to '/usr/lib/cblas.so.3' found (skipping)
warning: no library file corresponding to '/usr/lib/f77blas.so.3' found (skipping)
warning: no library file corresponding to '/usr/lib/lapack_atlas.so.3' found (skipping)
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/kaldiasr/nnet3.o build/temp.linux-x86_64-2.7/kaldiasr/nnet3_wrappers.o -L/home/machPred/phillip_workenv/speech_recognition/kaldi/tools/openfst/lib -L/home/machPred/phillip_workenv/speech_recognition/kaldi/src/lib -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector -lfst -o /home/test/py-kaldi-asr/kaldiasr/nnet3.so
/usr/bin/ld: cannot find -lkaldi-decoder
/usr/bin/ld: cannot find -lkaldi-lat
/usr/bin/ld: cannot find -lkaldi-fstext
/usr/bin/ld: cannot find -lkaldi-hmm
/usr/bin/ld: cannot find -lkaldi-feat
/usr/bin/ld: cannot find -lkaldi-transform
/usr/bin/ld: cannot find -lkaldi-gmm

Any idea where I may look for these files ?

**Comment by Cloud299** [comment]
Looked in setup.py and saw that it was looking for libatlas.so.3. I found it at /usr/lib/atlas-base. That error is gone. Thanks for the suggestion @svenha 

Having a different issue when running "make". 
warning: no library file corresponding to '/usr/lib/atlas.so.3' found (skipping)
warning: no library file corresponding to '/usr/lib/cblas.so.3' found (skipping)
warning: no library file corresponding to '/usr/lib/f77blas.so.3' found (skipping)
warning: no library file corresponding to '/usr/lib/lapack_atlas.so.3' found (skipping)
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/kaldiasr/nnet3.o build/temp.linux-x86_64-2.7/kaldiasr/nnet3_wrappers.o -L/home/test/kaldi/tools/openfst/lib -L/home/test/kaldi/src/lib -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector -lfst -o /home/test/py-kaldi-asr/kaldiasr/nnet3.so
/usr/bin/ld: cannot find -lkaldi-decoder
/usr/bin/ld: cannot find -lkaldi-lat
/usr/bin/ld: cannot find -lkaldi-fstext
/usr/bin/ld: cannot find -lkaldi-hmm
/usr/bin/ld: cannot find -lkaldi-feat
/usr/bin/ld: cannot find -lkaldi-transform

Any idea where I can find these files ? I can see libatlas.so.3 but not atlas.so.3, libcblas.so.3 but not cblas.so.3

**Comment by SanjeevKV** [comment]
Hey @Cloud299 
I am facing the same issue:
Cannot find any of the lkaldi-XXXX
Did you find a solution to this?

**Comment by gooofy** [comment]
looks like an issue with your kaldi installation and/or pkg-config setup. check out what

`pkg-config --libs kaldi-asr`

produces and make sure the -L paths are ok and contain the required libraries.

example output:

```
$ pkg-config --libs kaldi-asr
-L/opt/kaldi/src/lib -L/usr/lib64/atlas/ -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector -lsatlas -lfst  
```

libraries:

```
$ ls -l /opt/kaldi/src/lib
total 0
lrwxrwxrwx 1 root root 24 May  5 17:27 libkaldi-base.so -> ../base/libkaldi-base.so
lrwxrwxrwx 1 root root 26 May  5 17:27 libkaldi-chain.so -> ../chain/libkaldi-chain.so
lrwxrwxrwx 1 root root 36 May  5 17:27 libkaldi-cudamatrix.so -> ../cudamatrix/libkaldi-cudamatrix.so
lrwxrwxrwx 1 root root 30 May  5 17:27 libkaldi-decoder.so -> ../decoder/libkaldi-decoder.so
lrwxrwxrwx 1 root root 24 May  5 17:27 libkaldi-feat.so -> ../feat/libkaldi-feat.so
lrwxrwxrwx 1 root root 28 May  5 17:27 libkaldi-fstext.so -> ../fstext/libkaldi-fstext.so
lrwxrwxrwx 1 root root 22 May  5 17:27 libkaldi-gmm.so -> ../gmm/libkaldi-gmm.so
lrwxrwxrwx 1 root root 22 May  5 17:27 libkaldi-hmm.so -> ../hmm/libkaldi-hmm.so
lrwxrwxrwx 1 root root 30 May  5 17:27 libkaldi-ivector.so -> ../ivector/libkaldi-ivector.so
lrwxrwxrwx 1 root root 22 May  5 17:27 libkaldi-kws.so -> ../kws/libkaldi-kws.so
lrwxrwxrwx 1 root root 22 May  5 17:27 libkaldi-lat.so -> ../lat/libkaldi-lat.so
lrwxrwxrwx 1 root root 20 May  5 17:27 libkaldi-lm.so -> ../lm/libkaldi-lm.so
lrwxrwxrwx 1 root root 28 May  5 17:27 libkaldi-matrix.so -> ../matrix/libkaldi-matrix.so
lrwxrwxrwx 1 root root 26 May  5 17:27 libkaldi-nnet2.so -> ../nnet2/libkaldi-nnet2.so
lrwxrwxrwx 1 root root 26 May  5 17:27 libkaldi-nnet3.so -> ../nnet3/libkaldi-nnet3.so
lrwxrwxrwx 1 root root 24 May  5 17:27 libkaldi-nnet.so -> ../nnet/libkaldi-nnet.so
lrwxrwxrwx 1 root root 30 May  5 17:27 libkaldi-online2.so -> ../online2/libkaldi-online2.so
lrwxrwxrwx 1 root root 26 May  5 17:27 libkaldi-rnnlm.so -> ../rnnlm/libkaldi-rnnlm.so
lrwxrwxrwx 1 root root 26 May  5 17:27 libkaldi-sgmm2.so -> ../sgmm2/libkaldi-sgmm2.so
lrwxrwxrwx 1 root root 34 May  5 17:27 libkaldi-transform.so -> ../transform/libkaldi-transform.so
lrwxrwxrwx 1 root root 24 May  5 17:27 libkaldi-tree.so -> ../tree/libkaldi-tree.so
lrwxrwxrwx 1 root root 24 May  5 17:27 libkaldi-util.so -> ../util/libkaldi-util.so

```

**Comment by cosmicaug** [comment]
Same issue here. I'm using Mint 19.2 which is a Ubuntu 18.04 (Bionic Beaver) based distribution. I'm running an anaconda environment with Python 3.75 installed (but the same error was happening when I used a different environment running 3.6.9). 

The error message resembles Cloud299's error message ("Package atlas was not found in the pkg-config search path", etc.).

An  '/usr/lib/x86_64-linux-gnu' subdirectory exists in my system and it contains the 'libatlas.so.3' file as well as an 'atlas' subdirectory (with libblas & liblapack related files). There's also a '/usr/include/x86_64-linux-gnu/atlas' with headers. **There's no file named 'atlas.so.3' in my filesystem**.

`pkg-config --libs kaldi-asr`

gives:

```
Package atlas was not found in the pkg-config search path.
Perhaps you should add the directory containing `atlas.pc'
to the PKG_CONFIG_PATH environment variable
Package 'atlas', required by 'kaldi-asr', not found
```

Since there's a reference to '/usr/include/atlas' in setup.py and I lacked that directory in my system, I made a symbolic link to what looked like the correct subdirectory with:
`ln -s /usr/include/x86_64-linux-gnu/atlas /usr/include/atlas`

It didn't work. It just made my error message longer but it still complains about not finding the atlas package:
```
Collecting py-kaldi-asr
  Using cached https://files.pythonhosted.org/packages/b5/bb/0082185cfa67d63068358de9b1a65661c8dcdbe97e935809427d5881ea17/py-kaldi-asr-0.5.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/cosmicaug/anaconda3/envs/pykadiasr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3iuu2zct/py-kaldi-asr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3iuu2zct/py-kaldi-asr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-3iuu2zct/py-kaldi-asr/pip-egg-info
         cwd: /tmp/pip-install-3iuu2zct/py-kaldi-asr/
    Complete output (18 lines):
    Package atlas was not found in the pkg-config search path.
    Perhaps you should add the directory containing `atlas.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'atlas' found
    Package atlas was not found in the pkg-config search path.
    Perhaps you should add the directory containing `atlas.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'atlas', required by 'kaldi-asr', not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3iuu2zct/py-kaldi-asr/setup.py", line 99, in <module>
        **find_dependencies()),
      File "/tmp/pip-install-3iuu2zct/py-kaldi-asr/setup.py", line 72, in find_dependencies
        raise Exception("*** failed to find pkgconfig for kaldi-asr")
    Exception: *** failed to find pkgconfig for kaldi-asr
    looking for atlas library, trying pkg-config first...
    looking for atlas library, trying hard-coded paths...
    looking for atlas library, found it.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by chrisspen** [comment]
@cosmicaug That worked for me. Using your suggestion, I can install on Ubuntu 18 with:

     virtualenv -p python3.7 .env
    . .env/bin/activate
    sudo apt install libatlas-base-dev
    sudo ln -s /usr/include/x86_64-linux-gnu/atlas /usr/include/atlas
    pip install Cython
    pip install numpy py-kaldi-asr

Then I can `import kaldiasr` from Python.

**Comment by cosmicaug** [comment]
@chrisspen 

Nice! I wonder why I couldn't get it to work? I believe that I did the other steps as you describe.

What's your OS?

Addendum: Never mind, I see it's Ubuntu 18.
