### ISSUE TITLE
PyPi package: How to get source for specific version?

### ISSUE THREAD

**Issue by mpuels** [gooofy/py-kaldi-simple#16]
It's very convenient to be able to install `py-kaldi-asr` with `pip install py-kaldi-asr`. But how can I get the source code for a specific version of `py-kaldi-asr`? It would be nice if there'd be releases under https://github.com/gooofy/py-kaldi-asr/releases so that the version numbers correspond to the versions on PyPi.

If you don't want to release on GitHub, it would be nice if you'd create tags with the corresponding version numbers as names.

**Comment by gooofy** [comment]
release tagging is a great idea - i have just done so for 0.3.1

I would also like to host source packages (both deb and rpm) somewhere but I am not sure about the details yet.
