### ISSUE TITLE
Is there any script that can output the resulting lattice?

### ISSUE THREAD

**Issue by svenha** [gooofy/py-kaldi-simple#18]
The reason for asking is that the metric of **lattice oracle accuracy** (i.e. best accuracy achieved by any path in the lattice) is for some use cases much more useful than word error rate (WER) or sentence error rate (SER). Such use cases are: rescoring lattice with dialog history, rescoring lattice with parsing results etc.

**Comment by gooofy** [comment]
I am not aware of such a feature in py-kaldi-asr. However, kaldi itself comes with lots of example scripts and programs, so those might be worth checking out.
