### ISSUE TITLE
py-kaldi-asr version 0.5.0 fails on missing README.md file. 

### ISSUE THREAD

**Issue by pavelpe** [gooofy/py-kaldi-simple#22]
Newest version of py-kaldi-asr (0.5.0) fails on missing README.md file:
_File "/tmp/pip-build-gatbmr8h/py-kaldi-asr/setup.py", line 112, in <module>
        long_description     = open('README.md').read()_

W/o it pip install fails all the time

**Comment by gooofy** [comment]
thanks for the notice! :)

0.5.2 should include all missing files (it was not just README.md that was missing but also one header file related to the newly introduced GMM support).
