### ISSUE TITLE
Setup error:cannot find -lsatlas

### ISSUE THREAD

**Issue by pavelpe** [gooofy/py-kaldi-simple#23]
Setup of py-kaldi-asr fails on /usr/bin/ld: cannot find -lsatlas 
I've tried both 0.4.1 and 0.5.0 (after adding README.md manually) but both unsuccessfully.

_t-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/kaldiasr/nnet3.o build/temp.linux-x86_64-3.6/kaldiasr/nnet3_wrappers.o -L/usr/lib/atlas-base -L/home/user1/Kaldi/kaldi-asr/kaldi/tools/openfst/lib -L/home/user1/Kaldi/kaldi-asr/kaldi/src/lib -L/usr/lib/atlas-base -lsatlas -lkaldi-decoder -lkaldi-lat -lkaldi-fstext -lkaldi-hmm -lkaldi-feat -lkaldi-transform -lkaldi-gmm -lkaldi-tree -lkaldi-util -lkaldi-matrix -lkaldi-base -lkaldi-nnet3 -lkaldi-online2 -lkaldi-cudamatrix -lkaldi-ivector -lfst -lsatlas -o build/lib.linux-x86_64-3.6/kaldiasr/nnet3.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: cannot find -lsatlas
    /usr/bin/ld: cannot find -lsatlas
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-g++' failed with exit status 1_

kaldi-asr.pc and atlas.pc both configured correctly. 
All dependencies are installed either (Cython)

Any suggestions?

**Comment by gooofy** [comment]
I suspect an issue with your pkg-config setup here. what is the output of

pkg-config --libs --cflags atlas

on your setup?

**Comment by pavelpe** [comment]
You are totally right, for some reason I had it in my atlas.pc file. 
Tested now on latest py-kaldi-asr package, it successfully installed.

**Comment by gooofy** [comment]
cool - thanks for your feedback! :)
