### ISSUE TITLE
Input feature dimension mismatch

### ISSUE THREAD

**Issue by wuhaie** [gooofy/py-kaldi-simple#25]
hi guys
 when I trying to decode the chain model, there is a error and how fix it ?
ERROR ([5.4.155~1399-fdd8]:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:45) Input feature dimension mismatch: got 40 but network expects 43

**Comment by gooofy** [comment]
please provide more information - which kaldi version are you using, which model (german/english, revision/timestamp)?
are you using py-kaldi-asr or you own code to drive kaldi?

**Comment by wuhaie** [comment]
> please provide more information - which kaldi version are you using, which model (german/english, revision/timestamp)?
> are you using py-kaldi-asr or you own code to drive kaldi?

The kaldi version is fdd8441f3862b42956e7a9236b872378f748449c and I use my own trained model with pitch features，but I don't know where to add this 'pitch' opt.

**Comment by svenha** [comment]
Out of curiosity: is this a Chinese model? From which corpora?

This error message is discussed several times on https://groups.google.com/forum/#!forum/kaldi-help. Maybe you can find a proven solution there?

**Comment by gooofy** [comment]
take a look at class KaldiNNet3OnlineModel: __cinit__ in nnet3.pyx - this is where all the config files for the decoder are generated. you should be able to add additional options and/or generate additional config files here.

**Comment by wuhaie** [comment]
thanks all, it solved.I will close this issue.
