### ISSUE TITLE
atlas issue [again]

### ISSUE THREAD

**Issue by madkote** [gooofy/py-kaldi-simple#26]
hi,

i have experienced the atlas issue also.
It is similar to `Setup error:cannot find -lsatlas #23` and I think the readme must be updated.

Option 1
add `pkg-config` for `atlas` - most probably for various systems (in my case I use Ubuntu)

Option 2
skip the `atlas` in requirements in `pkg-config` for `kaldi-asr.pc`

thx,
r

**Comment by gooofy** [comment]
not sure what to add to the readme - it clearly states that the provided kaldi-asr.pc file is just an example and details depend on the OS used.

**Comment by madkote** [comment]
got it. But still the whole process is bit confusing:
* `atlas` and `pkg-config`
* setup process and shared libraries

I had to walk through almost all closed issues to find my way building and installing the package.

My advice would be to review the `README` and make it easier for people to use this package, which is actually very good.

thx, r
