### ISSUE TITLE
[Question] how to detect silence / endpoint ?

### ISSUE THREAD

**Issue by madkote** [gooofy/py-kaldi-simple#29]
Hi,

when passing a long wave or stream to the decoder, how to detect multiple sentences inside of the audio signal?

**Comment by madkote** [comment]
If I understood correctly, it depends on the decoder used?

**Comment by gooofy** [comment]
that task is usually called "voice activity detection" - take a look at webrtc's VAD as a starting point

**Comment by madkote** [comment]
@gooofy thanks for reply. you mean nltools repo?

I remember a chat with one of kaldi developers, there should be a function to detect end-of-speech | sentence boundary | silence -> once function is called and a "break" is detected it is possible to finalize the utterance and continue with next in the stream.

**Comment by gooofy** [comment]
nltools offers a wrapper FSM around webrtc but you could use webrtc directly just as well - whatever fits your application best.

I have no experience using kaldi for end of speech detection - it sure sounds interesting, but I guess you will need to check kaldi documentation and/or contact the kaldi user mailing list on that one.

**Comment by madkote** [comment]
@gooofy thx for reply. I have played with both and have decided for kaldi endpoint detection.
Thx and best,
r
