### ISSUE TITLE
RunTime error when performing WAV decode

### ISSUE THREAD

**Issue by benjaminjamesarm** [gooofy/py-kaldi-simple#31]
When running the [example script](https://github.com/gooofy/py-kaldi-asr#example-code), it performs perfectly on the supplied demo1.wav, demo2.wav etc.

However, when I supply my own .wav files, I get the following error:
```
Traceback (most recent call last):
  File "asr_test.py", line 13, in <module>
    if decoder.decode_wav_file(WAVFILE):
  File "kaldiasr/nnet3.pyx", line 207, in kaldiasr.nnet3.KaldiNNet3OnlineDecoder.decode_wav_file (kaldiasr/nnet3.cpp:4726)
  File "kaldiasr/nnet3.pyx", line 170, in kaldiasr.nnet3.KaldiNNet3OnlineDecoder.decode (kaldiasr/nnet3.cpp:3968)
RuntimeError
```

`RuntimeError` isn't particularly descriptive - is there a way I can more effectively get to the bottom of what's going on?
Thanks.

**Comment by gooofy** [comment]
just a wild guess: maybe your wav files are not in 16kHz, 16 bits int mono? you could try to convert them using sox:

sox in.wav -r 16000 -b 16 -c 1 out.wav

**Comment by benjaminjamesarm** [comment]
Bang on; thanks! Appreciate the quick response

**Comment by chrisspen** [comment]
I'm also getting this error, and my files are definitely in 16k mono, and I'm generating with that exact same sox command.

**Comment by chrisspen** [comment]
The error appears to be coming from a Cython/C-extension. Is it possible there might be some missing dependency that caused the py-kaldi-asr package to incorrectly compile without throwing an explicit error? It appeared to compile just fine for me.

**Comment by chrisspen** [comment]
Yeah, there seems to be some bug in how the py-kaldi-asr package is compiled for Python3.*. If I run `kaldi_decode_wav.py` on the same file, using Python2.7, it decodes perfectly.

Is Python3 support planned?
