### ISSUE TITLE
Cannot find OnlineNnet3DecodingConfig in the code

### ISSUE THREAD

**Issue by maelp** [gooofy/py-kaldi-simple#4]
When compiling I get this error

```
In file included from kaldisimple/nnet3.cpp:456:
kaldisimple/nnet3_wrappers.h:64:9: error: unknown type name
      'OnlineNnet3DecodingConfig'
        OnlineNnet3DecodingConfig                 nnet3_decoding_config;
```

and a grep on both the Kaldi code and py-kaldi does not show any definition for this class, do you know where this code should be defined?

**Comment by nshmyrev** [comment]
Kaldi reworked internals recently, it will not work anymore. Checkout earlier revision from git,

 commit bcc71b67d489a1766922c9caf2a54306755f1861
Author: Andreas Søeborg Kirkedal <dresen@gmail.com>
Date:   Thu Feb 9 21:59:16 2017 +0100

should work.

**Comment by maelp** [comment]
Thanks! would it be complicated to update to the new interface, or is it some light coding? I could do this if not everything has been changed

**Comment by nshmyrev** [comment]
It should be pretty trivial, though some changes might be required. You can see relevant change in https://github.com/kaldi-asr/kaldi/commit/16afe7ae7e69080f723b4ce5072f58a94c19e00c#diff-2c645c6b8bc71f7225117531d2755224 and see how online2-wav-nnet3-latgen-faster.cc was updated.

**Comment by maelp** [comment]
Do you know what the change was supposed to allow? it talks about looped decoder, is that a way to make the decoder faster when decoding online? I'm taking a look at the code to see if I can update the interface

**Comment by maelp** [comment]
@nshmyrev I updated the code and it compiles, but the `decoder->AdvanceDecoding()` in `nnet3_wrappers.cpp` crashes, do you have an idea where it could come from?

if you need, I updated the `Makefile` to compile on osX with the following:

```
CFLAGS = -std=c++11 -I$(KALDI_ROOT)/src -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -Wno-sign-compare \
		          -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_CLAPACK \
							-I$(KALDI_ROOT)/tools/openfst/include -g -Wno-deprecated-declarations \
							-Wno-unused-variable

LDFLAGS = -rdynamic -L$(KALDI_ROOT)/tools/openfst/lib -L$(KALDI_ROOT)/src/lib \
          -lfst -lclapack -lm -lpthread -ldl  -lkaldi-decoder \
		  -lkaldi-lat   -lkaldi-fstext   -lkaldi-hmm     -lkaldi-feat    -lkaldi-transform \
		  -lkaldi-gmm   -lkaldi-tree     -lkaldi-util    -lkaldi-thread  -lkaldi-matrix \
		  -lkaldi-base  -lkaldi-nnet3    -lkaldi-online2

```

and then I have to set the `DYLD_LIBRARY_PATH` to `kaldi/src/lib` when running scripts

**Comment by maelp** [comment]
My fork is at <https://github.com/maelp/py-kaldi-simple>

**Comment by maelp** [comment]
The bug seems to be random, as sometimes the decoding works, but most of the time it crashes, I wonder if this could be due to a threading option?

**Comment by nshmyrev** [comment]
> The bug seems to be random, as sometimes the decoding works, but most of the time it crashes, I wonder if this could be due to a threading option?

You can run under valgrind and provide output/stacktrace, it should be a memory corruption. Python does not have threads.

**Comment by maelp** [comment]
I solved it, it was the fact that some variables were not initialized in the constructor. I might push a PR but I want to change the code more

**Comment by gooofy** [comment]
@maelp: very nice work! please let me know once you feel your code is ready for a merge or you have patches you think I should apply. Thanks in advance! :)

**Comment by mariasmo** [comment]
hi maelp

i am stuck at the same issue. can you please let me know what fixes you had to make to get it working?

thanks

**Comment by mariasmo** [comment]
@maelp @gooofy @nshmyrev 

so i forked out goofy's repo and made the necessary changes to get your sample code compile for the latest kaldi source code.

even though it compiled i am pretty sure it will not run as there is an object that needs to be initialized.
i am relatively new to kaldi and am not sure how to init that object.

if any of you can please look into the changes and see what needs to be done to get it working that would be awesome.

once we get it working we can merge changes into goofy's repo.

thanks

**Comment by gooofy** [comment]
@mariasmo: finally found the time to check out what you have done and must say: I am very impressed! I had to do some minor adjustments to make it work with my current kaldi 5.1 setup here but other than that it worked right out of the box, very nice work!

I have pulled most of your changes now. Thanks again for your contribution!

**Comment by gooofy** [comment]
adapted the codebase to kaldi 5.2 now with lots of cleanups and improvements, so I will close this issue now.
