### ISSUE TITLE
linking issue when experimenting

### ISSUE THREAD

**Issue by fanskyer** [gooofy/py-kaldi-simple#5]
new to this python binding, but i followed the instructions and nnet3.so compiled successfully with kaldi 5.0.
However, when testing, import kaldisimple.nnet3, it shows import error, undefined symbol _ZTVN3fst11SymbolTableE, i already put the tools/openfst/lib into the LD_LIBRARY_PATH, but the issue is still there? anything i am missing? many thanks

**Comment by gooofy** [comment]
having no experience with kaldi 5.0 I would simply guess that version is too new (i.e. interfaces have changed so the binding code does not work out of the box anymore). please also check out issue #4 for details.

**Comment by fanskyer** [comment]
thanks, i read through an closed issue and i found my issue is very similar to it, i still used kaldi 5.0 as well as add this -Wl,-no-as-needed into LDFLAGS [ seems new version of GCC need it ] and then problem solved. thanks

**Comment by gooofy** [comment]
thank for the feedback - closing the issue.

**Comment by gargsanchit31** [comment]
I am facing the same issue. I don't know how to add the LDFLAGS. Can you help here?

**Comment by gooofy** [comment]
Take a look at the Makefile, here LDFLAGS are specified:

LDFLAGS = -rdynamic -lm -lpthread -ldl `pkg-config --libs kaldi-asr`
