### ISSUE TITLE
about setup.py

### ISSUE THREAD

**Issue by thetimeofblack** [gooofy/py-kaldi-simple#9]

**Comment by thetimeofblack** [comment]
I find that I can not run the setup.py 
and  I have checked the code. I find some problems about the /data/kaldi.asr 
package-config can not find the document nnet3.cpp

**Comment by thetimeofblack** [comment]
And I find that if I can not install the kaldi for py-nltools and I can not install py-nltools for zamia-ai so that the whole tools can not be used for my own project

**Comment by gooofy** [comment]
most common reason for this issue is not having cython installed, which is needed to generate nnet3.cpp. could you check that?

**Comment by thetimeofblack** [comment]
I have checked it and I have installed the cython, however the problem still exist that we lack the component of atlas, but I have not found the official software of the atlas for kaldi

**Comment by thetimeofblack** [comment]
I also want to confirm that atlas is a library for linear Matrix calculation ?

**Comment by gooofy** [comment]
ah, I see - so pkgconfig cannot find atlas? it depends on you distro how atlas packconfig ist done - some distros do not provide an atlas.pc file at all. in that case you can put one into your PKGCONFIGPATH manually. you can use mine as a template:

```
$ cat /usr/lib64/pkgconfig/atlas.pc
Name: atlas
Version: 3.10.2
Description: Debug information for package atlas
Cflags: -I/usr/include/atlas/
Libs: -L/usr/lib64/atlas/ -lsatlas

```

**Comment by gooofy** [comment]
the latest setup.py will try to auto-detect atlas if pkgconfig fails to provide information about it so providing your own atlas.pc should not be necessary anymore.
